theme: jekyll-theme-cayman
title: Chandra Kallakuri
description: Simplify [Products/Processes/Services] to Amplify [Value/Experience]

show_excerpts: true

show_downloads: true

social_links:
   twitter: _kallakuris
   github:  ckallakuri

header_pages:
  - contact.md
  - ideas.md
